[project]
name = "granian-reproducers"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = ["fastapi>=0.116.1", "granian[rloop,uvloop]>=2.5.1"]

[dependency-groups]
dev = ["mypy>=1.17.1"]

[tool.uv]
package = true

[tool.mypy]
files = ["granian_reproducers"]
